spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    source:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
      username: source
      password: 1234
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 30000
    target:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
      username: target
      password: 1234
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 10
        connection-timeout: 30000
    proxy:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
      username: proxy
      password: 1234
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 30000

sync:
  chunk-size-initial: 2000
  chunk-size-min: 500
  chunk-size-max: 10000
  lag-alert-threshold: 100000
  job-name: "ORDERS_SYNC"
  fixed-delay-ms: 60000
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8090