package com.example.sync;

import com.example.sync.batch.SyncJobExecutor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.sql.Timestamp;
import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class SyncIntegrationTest {

    @Autowired
    private SyncJobExecutor syncJobExecutor;

    @Autowired
    @Qualifier("sourceJdbcTemplate")
    private JdbcTemplate sourceJdbcTemplate;

    @Autowired
    @Qualifier("targetJdbcTemplate")
    private JdbcTemplate targetJdbcTemplate;

    @BeforeEach
    void setUp() {
        // H2 Oracle 모드용 스키마 생성
        sourceJdbcTemplate.execute("DROP TABLE IF EXISTS orders");
        sourceJdbcTemplate.execute("CREATE TABLE orders (id BIGINT PRIMARY KEY, order_no VARCHAR(50), customer_id BIGINT, status VARCHAR(20), amount DECIMAL(10,2), created_at TIMESTAMP)");
        
        targetJdbcTemplate.execute("DROP TABLE IF EXISTS orders_target");
        targetJdbcTemplate.execute("DROP TABLE IF EXISTS sync_checkpoint");
        targetJdbcTemplate.execute("DROP TABLE IF EXISTS batch_retry_queue");
        targetJdbcTemplate.execute("DROP TABLE IF EXISTS shedlock");

        targetJdbcTemplate.execute("CREATE TABLE orders_target (id BIGINT PRIMARY KEY, order_no VARCHAR(50), customer_id BIGINT, status VARCHAR(20), amount DECIMAL(10,2), created_at TIMESTAMP)");
        targetJdbcTemplate.execute("CREATE TABLE sync_checkpoint (job_name VARCHAR(100) PRIMARY KEY, last_id BIGINT DEFAULT 0, last_synced_at TIMESTAMP, processed_cnt BIGINT DEFAULT 0)");
        // AUTO_INCREMENT 대신 GENERATED BY DEFAULT AS IDENTITY 사용 (H2 2.x 호환)
        targetJdbcTemplate.execute("CREATE TABLE batch_retry_queue (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_ids CLOB, error_type VARCHAR(100), error_message CLOB, retry_count INT DEFAULT 0, max_retry INT DEFAULT 5, next_retry_at TIMESTAMP, status VARCHAR(20) DEFAULT 'PENDING')");
        targetJdbcTemplate.execute("CREATE TABLE shedlock (name VARCHAR(64) PRIMARY KEY, lock_until TIMESTAMP, locked_at TIMESTAMP, locked_by VARCHAR(255))");

        // 소스 데이터 삽입
        for (long i = 1; i <= 3; i++) {
            sourceJdbcTemplate.update("INSERT INTO orders (id, order_no, customer_id, status, amount, created_at) VALUES (?, ?, ?, 'CREATED', 100.0, ?)",
                    i, "ORD-" + i, 1000 + i, Timestamp.valueOf(LocalDateTime.now()));
        }
    }

    @Test
    void execute_H2환경에서도_전체동기화가_정상동작한다() {
        syncJobExecutor.execute();

        Integer targetCount = targetJdbcTemplate.queryForObject("SELECT COUNT(*) FROM orders_target", Integer.class);
        assertThat(targetCount).isEqualTo(3);

        Long lastId = targetJdbcTemplate.queryForObject("SELECT last_id FROM sync_checkpoint WHERE job_name = 'ORDERS_SYNC'", Long.class);
        assertThat(lastId).isEqualTo(3L);
    }
}
