-- FREEPDB1 PDB에서 3개 사용자 생성 (SYSDBA로 실행)
CREATE USER source IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO source;

CREATE USER target IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO target;

CREATE USER proxy IDENTIFIED BY "1234";
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO proxy;
